name: Cross Compile Qt6 App using MXE from Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar cmake ninja-build pkg-config

      - name: Download MXE Qt6 Release
        run: |
          curl -L -o mxe-qt6.tar.gz https://github.com/CSReviser/mxe-builder/releases/download/mxe-qt6-v1/mxe-qt6-x86_64.tar.gz
          mkdir -p mxe
          tar -xzf mxe-qt6.tar.gz -C mxe --strip-components=1

      - name: Fix broken MXE symlinks
        run: |
          find mxe/usr/bin -type l | while read link; do
            target=$(readlink "$link")
            if [[ ! -e "$target" ]]; then
              abs_target=$(basename "$target")
              real_target=$(find mxe/usr -name "$abs_target" | head -n1)
              if [[ -n "$real_target" && -f "$real_target" ]]; then
                rm "$link"
                cp "$real_target" "$link"
                echo "Fixed $link -> $real_target"
              fi
            fi

      - name: Build with CMake + MXE (Qt6)
        env:
          MXE_PATH: ${{ github.workspace }}/mxe
        run: |
          export PATH=$MXE_PATH/usr/bin:$PATH
          export TOOLCHAIN_FILE=$MXE_PATH/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} \
            -DCMAKE_PREFIX_PATH="$MXE_PATH/usr/x86_64-w64-mingw32.static/qt6" \
            -DQT_HOST_PATH="$QT_HOST_PATH" \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt6-Windows-App
          path: build/*.exe