name: MacOS M1 C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.*
        modules: 'qtcharts'
        
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S ./ -B ./ -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
    - name: make
      run: make
      
    - name: Make CaptureStream2 executable
      run: |
        wget -qO ffmpeg7arm.zip https://www.osxexperts.net/ffmpeg7arm.zip
        7z e ffmpeg7arm.zip ffmpeg -o./CaptureStream2.app/Contents/MacOS/
        chmod -R 755 ./CaptureStream2.app
        xattr -rc ./CaptureStream2.app

    - name: Tar files
      run: tar cvf CaptureStream2.tar ./CaptureStream2.app
      
    - name: mkdir
      run: mkdir -p ./build/MacCaptureStream2
    - name: cp
      run: mv ./CaptureStream2.app ./build/MacCaptureStream2/

    - name: Create dmg
      uses: QQxiaoming/create-dmg-action@v0.0.2
      with:
        name: CaptureStream2-MacOS
        srcdir: ./build

    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-M1
        path: CaptureStream2-MacOS.dmg
     
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Univarsal-arm-ffmpeg
        path: CaptureStream2.tar
