name: 2-1. Windows qt5.15 qmake C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest
    defaults:
        run:
            shell: msys2 {0}
            
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        install-deps: 'true'
       
    - uses: actions/checkout@v4
    - name: qmake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: | 
        mkdir -p ./build/WinCaptureStream2/plugins
        qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
    - name: make
      run: make
     
    - name: Make CaptureStream2 executable
      run: chmod -R 755 ./CaptureStream2.exe
    - name: cp
      run: |
        mkdir -p ./lib
        mkdir -p ./plugins
        ../Qt/6.5.3/mingw_64/bin/windeployqt6.exe ./CaptureStream2.exe --libdir ./lib --plugindir ./plugins --no-system-d3d-compiler --no-quick-import
        cp ./qss_files/stylesheet-win.qss ./build/WinCaptureStream2/
        cp ./CaptureStream2.exe ./build/WinCaptureStream2/
        cp -r ./lib/*.dll ./build/WinCaptureStream2/
        cp -r ./plugins ./build/WinCaptureStream2/

    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
      with:
        version: 5.1

    - name: cp
      run: | 
        cp "C:\hostedtoolcache\windows/FFmpeg/ffmpeg.exe" ./build/WinCaptureStream2/

    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-windows
        path: ./build
