name: Windows qt6.5 cmake C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest
    defaults:
        run:
            shell: msys2 {0}
            
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.*
        modules: 'qtcharts'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        tools: 'tools_mingw,qt.tools.win64_mingw810'
        dir: '${{github.workspace}}/qt/'
        install-deps: 'true'

    - uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-toolchain
        msystem: mingw64
        release: false
        
    - uses: actions/checkout@v4
    - name: cmake
      run: D:\a\CaptureStream2\CaptureStream2\qt\Qt\6.5.3\mingw_64\bin\qmake CaptureStream2.pro
    - name: make
      run: make
      
    - name: Make CaptureStream2 executable
      run: chmod -R 755 ./CaptureStream2.exe
 
    - name: mkdir
      run: mkdir ./build
    - name: cp
      run: mv ./CaptureStream2.exe ./build/
    - name: cp
      run: cp ./qss_files/stylesheet-win.qss ./build/
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-windows
        path: ./build

