name: Windows qt6.5 cmake C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest
    defaults:
        run:
            shell: msys2 {0}
            
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.3
        modules: 'qtcharts'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        tools: 'tools_mingw,qt.tools.win64_mingw810'
        install-deps: 'true'
       
    - uses: actions/checkout@v4
    - name: cmake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: | 
        mkdir -p ./build/WinCaptureStream2
        cmake -S . -B ./build && cmake --build ./build --target all
        
    - name: Make CaptureStream2 executable
      run: chmod -R 755 ./build/CaptureStream2.exe
    - name: cp
      run: |
        cp -r ../Qt/6.5.3/mingw_64/plugins/platforms ./build/WinCaptureStream2/plugins/platforms
        cp -r ../Qt/6.5.3/mingw_64/plugins/tls ./build/WinCaptureStream2/plugins/tls
        cp -r ../Qt/6.5.3/mingw_64/bin/Qt6Core.dll ./build/WinCaptureStream2/
        cp -r ../Qt/6.5.3/mingw_64/bin/Qt6Gui.dll ./build/WinCaptureStream2/
        cp -r ../Qt/6.5.3/mingw_64/bin/Qt6Network.dll ./build/WinCaptureStream2/
        cp -r ../Qt/6.5.3/mingw_64/bin/Qt6Widgets.dll ./build/WinCaptureStream2/
        cp ./qss_files/stylesheet-win.qss ./build/WinCaptureStream2/
          
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-windows
        path: ./build

