name: Ubuntu22 qt6.5 cmake C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.0
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtcharts'
    - name: ubuntu install GL library
      run: sudo apt-get install -y libglew-dev libglfw3-dev build-essential libgl1-mesa-dev libxcb-cursor-dev

    - uses: actions/checkout@v4
    - name: build ubuntu
      run: |
          mkdir local
          cp -r ../Qt/6.5.0/gcc_64/lib ./local/
          cp -r ../Qt/6.5.0/gcc_64/plugins ./local/
          cmake . . && make
          mkdir -p ./build/LinCaptureStream2
          cp -r  ./local .//build/LinCaptureStream2/
          cp -r  CaptureStream2 ./build/LinCaptureStream2/
          cp -r  ./qss_files/stylesheet-ubu.qss ./build/LinCaptureStream2/

    - name: Install LinuxDeployQt
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage
        dir: ${{ github.workspace }}


    - name: build ubuntu
      run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
          ./linuxdeploy-x86_64.AppImage --appdir ./build/LinCaptureStream2/ --executable ./CaptureStream2 --plugin qt
          cp -r ./qss_files/stylesheet-ubu.qss ./build/LinCaptureStream2/usr/bin/

      
    - name: Make CaptureStream2 executable
      run: chmod -R 755 ./build/LinCaptureStream2/
     
    - uses: actions/upload-artifact@v4
      with:
        name: LinCaptureStream2
        path: ./build/

