name: Qt6 Desktop App Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.*
        modules: 'qtcharts'

    - name: Configure Project
      run: |
        mkdir -p build
        cd build
        cmake -S ../ -B ./ -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        make

    - name: Make CaptureStream2 executable
      run: |
        cd build
        wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-5.1.2.7z
        7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
        chmod -R 755 ./CaptureStream2.app

    - name: mkdir
      run: |
        mkdir -p ./build/MacCaptureStream2
        cp -r ./build/CaptureStream2.app ./build/MacCaptureStream2
        
    - name: Tar files
      run: |
        cd build
        tar cvf CaptureStream2.tar ./MacCaptureStream2

    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-macos-Univarsal-qt68
        path: CaptureStream2.tar
        
    - name: Run Tests
      run: |
        cd build/tests
        ./AppStartTest
