name: 1a.MacOS 14 qt5.15 Intel qmake C/C++ CI

on:
  workflow_dispatch:
    inputs:
      yyyymmdd:
        description: 'Release date (yyyymmdd)'
        required: true

jobs:
  mac_qt5_build:
    runs-on: macos-14

    steps:
      - name: Set release variables
        id: setvars
        run: |
          tag=${{ github.event.inputs.yyyymmdd }}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark repo as safe
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Update GitHub CLI
        run: |
          brew install gh || brew upgrade gh

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.*
          modules: 'qtcharts'
          extra: '--external 7z'

      - name: qmake
        run: |
          qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
          make
          wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z
          7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
          chmod -R 755 ./CaptureStream2.app
          mkdir -p ./build/tmp/MacCaptureStream2
          cp ./icon.icns ./CaptureStream2.app/Contents/Resources/
          cp ./qss_files/stylesheet-mac.qss ./CaptureStream2.app/Contents/MacOS/
          mv ./CaptureStream2.app ./build/tmp/MacCaptureStream2/
          cp -r ./qss_files/License ./build/tmp/MacCaptureStream2/
          
      - name: Create DMG file
        run: |
          cd build
          hdiutil create -volname MacCaptureStream2 \
                      -srcfolder tmp \
                      -ov -format UDZO \
                      "CaptureStream2-MacOS-qt5-${{ github.event.inputs.yyyymmdd }}.dmg"


      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: build/CaptureStream2-MacOS-qt5-${{ github.event.inputs.yyyymmdd }}.dmg
          tag_name: ${{ needs.mac_build.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
