name: Ubuntu22 Qt 6.8 CMake C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    # Qtをインストール
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.0
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtcharts'
        cache: false

    # 必要なGLライブラリをインストール
    - name: Install GL libraries
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt-get install -y libglew-dev libglfw3-dev build-essential libgl1-mesa-dev libxcb-cursor-dev

    # リポジトリをチェックアウト
    - uses: actions/checkout@v4

    # CMakeでビルド構成を生成
    - name: Configure and Build with CMake
      run: |
        mkdir -p build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel

    # 必要なファイルをコピー
    - name: Copy dependencies and resources
      run: |
        mkdir -p build/LinCaptureStream2
        cp -r ./qss_files/stylesheet-ubu.qss build/LinCaptureStream2/
        cp build/CaptureStream2 build/LinCaptureStream2/

    # LinuxDeployQtをインストール
    - name: Install LinuxDeployQt
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage

    # AppImageを作成
    - name: Create AppImage
      run: |
        mkdir -p appdir/usr/bin
        cp build/LinCaptureStream2/CaptureStream2 appdir/usr/bin/
        cp build/LinCaptureStream2/stylesheet-ubu.qss appdir/usr/bin/
        ./linuxdeploy-x86_64.AppImage --appdir appdir --output appimage --plugin qt

    # アーティファクトをアップロード
    - uses: actions/upload-artifact@v4
      with:
        name: LinCaptureStream2
        path: appdir/