name: 1. MacOS 14 qt6.5 M1(ARN) cmake C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.5.*
        modules: 'qtcharts'

    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
      with:
        version: 71
        
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S ./ -B ./ -DCMAKE_OSX_ARCHITECTURES="arm64"
    - name: make
      run: make
      
    - name: Make CaptureStream2 executable
      run: |
        wget -qO ffmpeg7arm.zip https://www.osxexperts.net/ffmpeg71arm.zip
        7z e ffmpeg7arm.zip ffmpeg -o./CaptureStream2.app/Contents/MacOS/
        chmod -R 755 ./CaptureStream2.app
        xattr -rc ./CaptureStream2.app
 
    - name: mkdir
      run: mkdir -p ./build/MacCaptureStream2

    - name: Tar files
      run: tar cvf CaptureStream2.tar ./CaptureStream2.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-ARM-qt65
        path: CaptureStream2.tar
