name: MacOS 15 qt5.15 Intel qmake C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-15

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.*
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v4
    - name: qmake
      run: qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
    - name: make
      run: make
      
    - name: Make CaptureStream2 executable
      run: |
        wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-5.1.2.7z
        7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
        chmod -R 755 ./CaptureStream2.app

    - name: mkdir
      run: mkdir -p ./build/MacCaptureStream2
    - name: cp icon
      run: cp ./icon.icns ./CaptureStream2.app/Contents/Resources/
    - name: cp qss
      run: cp ./qss_files/stylesheet-mac.qss ./CaptureStream2.app/Contents/MacOS/

    - name: Tar files
      run: tar cvf CaptureStream2.tar ./CaptureStream2.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-macos14-qt5-Intel
        path: CaptureStream2.tar
