name: macOS Qt GUI Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Homebrew
      run: |
        echo "Updating Homebrew..."
        brew update

    - name: Install Qt
      run: |
        echo "Installing Qt..."
        brew install qt

    - name: Add Qt to PATH
      run: |
        echo "Adding Qt to PATH..."
        echo "PATH=$(brew --prefix qt)/bin:$PATH" >> $GITHUB_ENV

    - name: Build Qt GUI Application
      run: |
        echo "Building the application..."
        mkdir -p build
        cd build
        cmake . ../
        make

    - name: Run Tests
      run: |
        echo "Running tests..."
        cd build
        ./CaptureStream2.app