name: 1. MacOS 14 qt6.4 Univarsal cmake C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.4.1
        modules: 'qtcharts'

    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
      with:
        version: 5.1.2
        
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S ./ -B ./ -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
    - name: make
      run: make
      
    - name: Make CaptureStream2 executable
      run: |
        wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-5.1.2.7z
        7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
        chmod -R 755 ./CaptureStream2.app
        xattr -rc ./CaptureStream2.app
 
    - name: mkdir
      run: mkdir -p ./build/MacCaptureStream2

    - name: Tar files
      run: tar cvf CaptureStream2.tar ./CaptureStream2.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Univarsal-qt64
        path: CaptureStream2.tar
