name: 1.MacOS 14 qt5.15 Intel qmake C/C++ CI

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: macos-14

    steps:
    # リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4

    # Qtをインストール
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.*
        modules: 'qtcharts qtscript qtwebengine'
        extra: '--external 7z'
        
    - uses: actions/checkout@v4
    - name: qmake
      run: qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
    - name: make
      run: make
      
    # CaptureStream2の実行可能ファイルを準備
    - name: Make CaptureStream2 executable
      run: |
        wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z || { echo "Failed to download FFmpeg"; exit 1; }
        7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/ || { echo "Failed to extract FFmpeg"; exit 1; }
        chmod -R 755 ./CaptureStream2.app

    - name: mkdir
      run: mkdir -p ./build/MacCaptureStream2
    - name: cp icon
      run: cp ./icon.icns ./CaptureStream2.app/Contents/Resources/
    - name: cp qss
      run: cp ./qss_files/stylesheet-mac.qss ./CaptureStream2.app/Contents/MacOS/

    - name: Tar files
      run: tar cvf CaptureStream2.tar ./CaptureStream2.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-macos14-qt5-Intel
        path: CaptureStream2.tar
