name: Qt6.5 GUI App CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Qt6.5
      run: |
        wget https://download.qt.io/official_releases/qt/6.5/6.5.0/qt-opensource-mac-x64-6.5.0.dmg
        hdiutil attach qt-opensource-mac-x64-6.5.0.dmg
        sudo installer -pkg /Volumes/Qt6.5.0/Qt6.5.0.pkg -target /

    - name: Build Qt6 application
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=/path/to/qt/6.5 ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure